# Generated by Django 4.1.1 on 2022-10-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
