# Generated by Django 2.2.12 on 2022-10-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_system', '0003_user_alter_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddrArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'addr_area',
                'managed': False,
            },
        ),
    ]
