# Generated by Django 2.2.12 on 2022-11-16 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water_system', '0005_roots'),
    ]

    operations = [
        migrations.AddField(
            model_name='workaction',
            name='tele',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='water_system.Work'),
        ),
    ]
