# Generated by Django 2.2.12 on 2022-11-17 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water_system', '0008_auto_20221117_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraction',
            name='kind',
            field=models.ForeignKey(blank=True, db_column='kind', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='water_system.Water'),
        ),
    ]
