# Generated by Django 4.1.3 on 2022-11-22 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water_system', '0010_alter_customer_name_alter_roots_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.ForeignKey(blank=True, db_column='name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='water_system.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
