# Generated by Django 4.1.3 on 2022-11-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_system', '0011_alter_customer_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraction',
            name='id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
